### ISSUE TITLE
get_all_dataset_ids to return string instead of RDF

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#13]
Unless there is a compelling reason to keep the RDF (which our audience may not know what it is), the function `get_all_dataset_ids` should return a list of strings. 

The workaround for now:

`ids_str = [str(i) for i in d2.get_all_dataset_ids()] `

**Comment by varunratnakar** [comment]
Fixed in https://github.com/LinkedEarth/pylipd/commit/8fc084dc6707269a56f4d97291de3814d3c4c50f
