### ISSUE TITLE
need to add .pop() and .remove() to LiPD object

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#16]
Need to have some ways to remove records from a LiPD object, given a dataset name

- .pop() should pop is out into a new object
- .remove() should just remove from the object either in place, or by creating a new object.

**Comment by varunratnakar** [comment]
Added with https://github.com/LinkedEarth/pylipd/commit/6817dd080e0c61bca677e8c6ec351b3eca9759f6
