### ISSUE TITLE
ProxySystem/Proxy System model should no longer exist

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#22]
The `lipd_to_rdf` schema should no longer use or try to guess archiveType/ProxyObservation or InferredVariable. But archiveType should be attached to the dataset. proxy now has a proxyName in the Lipd file themselves. Should use that for the schema.

**Comment by varunratnakar** [comment]
There are a lot of proxy based keywords in there.. I'm not sure how to map it to the ontology. We need to talk about this.

**Comment by khider** [comment]
Done with the new ontology
