### ISSUE TITLE
LiPD object should return a BiBTex

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#23]
Return a BiBTex based on all publications in the object.

**Comment by varunratnakar** [comment]
Initial work:
https://github.com/LinkedEarth/pylipd/commit/18230b6fb2598120c85c11194b9104243e79b39c

Todo:
If DOI given, use doi to fetch bibtex (requires internet)

**Comment by khider** [comment]
Done in: https://github.com/LinkedEarth/pylipd/commit/1463633e4d816697257a0cfdfd3cf782949c6c9b
