### ISSUE TITLE
Error on get_timeseries

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#26]
For this particular [record](https://lipdverse.org/lipdverse/current_version/Ocn-WEqPacific.Stott.2007.html), there is an error when trying to get the timeseries, which seems related to Uncertainty. 

To reproduce:

```
from pylipd.lipd import LiPD

L = LiPD()
data = ['https://lipdverse.org/data/TjhHrDv0LQ4aazHolZkR/1_0_0//Ocn-WEqPacific.Stott.2007.lpd']
L.load(data)

ts_list = L.get_timeseries(L.get_all_dataset_names())
```

**Comment by varunratnakar** [comment]
Uncertainty is a string in this one:

**Comment by varunratnakar** [comment]
Fixed with

**Comment by khider** [comment]
Apparently uncertainty can be both float or string
