### ISSUE TITLE
Bug with `doi` field when using `.get_timeseries`

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#37]
When using `get_timeseries` to expand properties into a dictionary for each column, there is a duplicate 'doi' for publication. One is called `pub1_doi` and seems to contain the actual doi. The other is called  `pub1_DOI` and seems the be stuck at `"hello"`.

To reproduce:

```
from pylipd.lipd import LiPD
url1 = 'https://lipdverse.org/data/iso2k100_CO04LIRA/1_0_2//CO04LIRA.lpd'
url2 = 'https://lipdverse.org/data/ch2kTA18TAS01/1_0_2//TA18TAS01.lpd'


data_url = [url1,url2]

D1 = LiPD()
D1.load(data_url)

ts = D1.get_timeseries(D1.get_all_dataset_names())
```

**Comment by varunratnakar** [comment]
I don't see the example Deborah

**Comment by khider** [comment]
Re-vist get_timeseries.

**Comment by khider** [comment]
@varunratnakar Bug is still present. Using the example above, you get the following:

![image](https://github.com/user-attachments/assets/f1cb9fef-2b1e-497f-a8a9-0758790b6a6f)

**Comment by varunratnakar** [comment]
Should be fixed with: https://github.com/LinkedEarth/pylipd/commit/5644ed517194f8367baf68220fc2b1284f22423d
