### ISSUE TITLE
`get_location` functionality

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/pylipd#40]
One of the main things I'm interested in when working with lipd objects is the location of records. Currently its possible to get at this info in a somewhat hacky way via the `get_timeseries` method call, but this returns lots of extraneous info as well. It would be nice to have a specific method (`get_location` or `get_position` or something) to pull all the latitude/longitude information from a lipd object into a dataframe alongside the associated dataset name.

**Comment by khider** [comment]
Will be done in #45

**Comment by khider** [comment]
Done in [c882a5f](https://github.com/LinkedEarth/pylipd/commit/c882a5f463fd0603e87a3f2dc31009a0d70efbee)
