### ISSUE TITLE
`get_timeseries` returning empty dictionary/dataframe

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/pylipd#42]
Running the following code currently returns an empty list (pylipd==1.3.2):

filename = 'https://github.com/LinkedEarth/pylipdTutorials/raw/main/data/Crystal.McCabe-Glynn.2013.lpd'
D = LiPD()
D.load(filename)
ts = D.get_timeseries(D.get_all_dataset_names())

This seems to be a problem with other datasets I've run into as well, which I'm happy to provide files for if need be! This seemed the most accessible example.

**Comment by alexkjames** [comment]
@khider recommended assigning you @varunratnakar for this one

**Comment by varunratnakar** [comment]
Fixed in 1.3.3
https://github.com/LinkedEarth/pylipd/commit/1c9e86d2f04b894b20bbc00a51c2ada56fa20569
