### ISSUE TITLE
"wood" vs "tree" in LiPD

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#57]
The proper vocabulary name for this archiveType is `wood` per [https://lipdverse.org/vocabulary/archivetype/](https://lipdverse.org/vocabulary/archivetype/). Therefore, for filtering purposes, one need to use `wood` as in: 

![image](https://github.com/LinkedEarth/pylipd/assets/11758571/775d7c55-c4c2-4165-abe2-421394e8ac1a)

However, when using the `get_timeseries_essentials` method, the archiveType is still `tree`. This is going to be confusing.

![image](https://github.com/LinkedEarth/pylipd/assets/11758571/42889dd3-fba3-4d26-a056-5f42602078bd)

I suspect that `tree` is forced from `wood` somewhere in the code base.

**Comment by khider** [comment]
To reproduce, used the Pages2k folder from the [tutorials](https://github.com/LinkedEarth/pylipdTutorials/tree/main/data)

**Comment by varunratnakar** [comment]
I get the archiveType as "Wood" now.

<img width="1059" alt="Screenshot 2024-05-11 at 3 16 48 PM" src="https://github.com/LinkedEarth/pylipd/assets/27664194/3ddb9dcb-7965-4d0e-b896-2fa48e285552">

**Comment by khider** [comment]
I still don't

![image](https://github.com/LinkedEarth/pylipd/assets/11758571/6bdcb857-98ef-4550-8b02-7bb90e9e444f)

**Comment by varunratnakar** [comment]
<img width="1161" alt="Screenshot 2024-05-14 at 12 00 22 PM" src="https://github.com/LinkedEarth/pylipd/assets/27664194/14feddc7-16ac-43e6-87e0-e2c76008c65b">
It is still working for me.. Could you paste the whole code that you are running ?

**Comment by khider** [comment]
It's the one attached to `LiPDSeries`, sorry, just realized this

**Comment by varunratnakar** [comment]
Ah ok. So it's the archiveType attached to variables. I've added a parsing step for archiveType at the variable level as well. Please try now.

**Comment by khider** [comment]
All good!
