### ISSUE TITLE
`get_all_variable_names()` function should be expanded to signal wether the name is controlled 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#60]
Right now, this function returns a list. Should we expand it to let a user know that it is part of the controlled vocabulary and that it may have been changed upon loading. Could return a list of two arrays or two arrays.

**Comment by varunratnakar** [comment]
Hmm, we don't keep the original names. Do we want to keep them ?

**Comment by varunratnakar** [comment]
I've added an option "standardize" in the LiPD load, which indicates whether we want to standardize, or not. By default, it is True

**Comment by khider** [comment]
let me create a non-standard file and try it out.

**Comment by khider** [comment]
Works with old files from the PyleoclimPaper repository.
