### ISSUE TITLE
BUG: `get_timeseries_essentials` Cannot unpack from a list 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#63]
To reproduce: 

```#Create a path to the data
filename = '../data/Crystal.McCabe-Glynn.2013.lpd'

#Initialize the lipd object
D = LiPD()

#Load the data
D.load(filename)

ensemble_df = D.get_ensemble_tables()

df = D.get_timeseries_essentials(D.get_all_dataset_names(), mode='paleo')

```

Data here: https://github.com/LinkedEarth/PyleoTutorials/tree/main/data

**Comment by varunratnakar** [comment]
get_timeseries_essentials seems to take only 1 dataset at a time. This works
`
df = lipd.get_timeseries_essentials(lipd.get_all_dataset_names()[0], mode='paleo')
`

Do we need it to work for multiple datasets ?

**Comment by khider** [comment]
Yes, needs to work for multiple datasets

**Comment by varunratnakar** [comment]
Should be fixed with this: https://github.com/LinkedEarth/pylipd/commit/3cbcee0672002fcec356b74f86e196cb80b79610
