### ISSUE TITLE
Loading a file with ensemble tables takes a long time

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#7]
I tried to load [this file](https://github.com/LinkedEarth/PyleoclimPaper/blob/main/Orbital%20Cycles/data/ODP846.Lawrence.2006.lpd) which contains an ensemble table, but it never loaded. Not sure if it's trying to represent each column as a variable but we should prevent it from doing so.

**Comment by varunratnakar** [comment]
Fixed in https://github.com/LinkedEarth/pylipd/commit/8c185076f3ebe7ff96c4019c41301f077fe71f63

**Comment by khider** [comment]
Tried it in a notebook and it sent my computer into a panicked loop of warnings

**Comment by khider** [comment]
It is the `if __name__=="__main__":` that sends the notebook into an infinite loop of warnings.

**Comment by khider** [comment]
Actually all files are sending the notebook in an infinite loop of warnings: 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/11758571/218589460-d547906f-be05-47b1-b152-cae527b9206c.png">

**Comment by khider** [comment]
But the loading works within Spyder.
